<?php
$colored_background_important = array(
    '#wp-submit',
    '.progress-bar',
    '#page-wrapper .wcContainer .wcMessage.wcCurrentUserMessage .wcMessageContent',
    'button[type="submit"]',
    '#content-container div.item-list-tabs ul li.selected a',
    ' #main-content .bbb-join input[type=submit]',
    ' .btn.btn-default',
    '#buddypress ul#members-list li div.item-avatar span.member-role',
    ' #main-content span.label',
    ' #main-footer span.label',
    ' #content-container div.item-list-tabs ul li.selected a',
    ' #content-container div.item-list-tabs ul li.selected a',
    ' #content-container div.item-list-tabs ul li.current a',
    ' #main-content #buddypress ul.button-nav li a',
    ' .woocommerce #content-container #respond input#submit',
    ' .woocommerce #content-container a.button',
    ' .woocommerce #content-container button.button',
    ' .woocommerce #content-container input.button',
    ' #content-container .woocommerce input.button:hover',
    ' .woocommerce #content-container nav.woocommerce-pagination ul li a',
    ' .woocommerce #content-container div.product p.price .amount',
    ' #nav-cart-trigger .amount',
    ' #content-container .woocommerce a.button',
    ' .woocommerce #respond input#submit.alt',
    ' .woocommerce a.button.alt',
    ' .woocommerce button.button.alt',
    ' .woocommerce input.button.alt',
    ' .woocommerce #respond input#submit.alt:hover',
    ' .woocommerce a.button.alt:hover',
    ' .woocommerce button.button.alt:hover',
    ' .woocommerce input.button.alt:hover',
    ' #right-sidebar .buttons a',
    ' .woocommerce .widget_price_filter .ui-slider .ui-slider-handle',
    ' .woocommerce .widget_price_filter .ui-slider .ui-slider-range',
    ' .woocommerce-shortcode .woocommerce .flex-direction-nav a',
    ' .it-exchange-product-price ins',
    ' #geodir-wrapper .geodir-viewall',
    ' .single-gd_place .geodir-post_left a',
    ' .single-gd_place .geodir-post_right a'
);